version: '3'

services:
  app:
    build: ./

    container_name: 'onyx-back'
    image: onyx-back

    ports:
      - '8080:8080'

    links:
      - redis:redis

    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=production

    volumes:
      - 'D:/Progects/Onyx/last-rest-api:/data'

  redis:
    container_name: 'redis'
    image: redis:latest

    expose:
      - 6379

    volumes:
      - 'D:/Progects/Onyx/last-rest-api:/data'

    command: ['redis-server', '--bind', 'redis', '--port', '6379']
