apiVersion: v1
kind: Service
metadata:
  labels:
    app: onyx-back
  name: onyx-back-http
spec:
  ports:
    - name: 'http'
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: onyx-back
  type: NodePort
